options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/planethorse/planet-horse-repo/planet-horse-backend:$SHORT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/planethorse/planet-horse-repo/planet-horse-backend:$SHORT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - >
          gcloud run deploy planet-horse-backend
          --image=us-central1-docker.pkg.dev/planethorse/planet-horse-repo/planet-horse-backend:$SHORT_SHA
          --region=us-central1
          --platform=managed
          --vpc-connector=planet-horse-connector
          --set-env-vars="DISCORD_REDIRECT_URI=${_DISCORD_REDIRECT_URI},DISCORD_CLIENT_SECRET=${_DISCORD_CLIENT_SECRET},DISCORD_CLIENT_ID=${_DISCORD_CLIENT_ID},JWT_SECRET=${_JWT_SECRET},SITE_DOMAIN=${_SITE_DOMAIN},SITE_URL=${_SITE_URL},NODE_ENV=${_NODE_ENV},DATABASE_URL=${_DATABASE_URL},MORALIS_API_KEY=${_MORALIS_API_KEY},NFT_CONTRACT_ADDRESS=${_NFT_CONTRACT_ADDRESS},NFT_CONTRACT_ADDRESS_OFH=${_NFT_CONTRACT_ADDRESS_OFH},RONIN_RPC_URL=${_RONIN_RPC_URL}"
          --add-cloudsql-instances=planethorse:us-east1:planet-horse-db-us

images:
  - us-central1-docker.pkg.dev/planethorse/planet-horse-repo/planet-horse-backend:$SHORT_SHA